config/routes.rb
Rails.application.routes.draw do
  resources :reviews, only: [:index, :show, :new, :create]

  scope "(:locale)", locale: /en|vi/ do
  resources :payment, only: [:index, :show]
  root 'home#index'
  resources :product, only: [:index, :show]
  resources :order, only: [:show, :destroy]
  resources :category
  # resources :order_item, only: [:create, :update, :destroy]
  resources :order_item
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  namespace :admin do 
    resources :categories
    resources :products, only: [:edit, :update, :show, :destroy]
    root 'categories#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :price, :discount, :description, :name, :category_id, :image, :trademark
  has_many :products, :dependent => :destroy
  validates :name_ct, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  def self.show
    Category.all
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :reviews
  mount_uploader :image, ImageUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [ :customer, :admin ]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :reviews

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order, :subtotal
  before_action :set_locale

  def skiplayout
    @skip_layout = true
  end

  def subtotal
    current_order.order_items.map{|k| k.product.price*k.quantity}.sum
  end

  def current_order
    if session[:order_id]
       Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def is_admin?
    if current_user.role.eql? 'admin'
    else
      redirect_to root_url
     end
  end
#  I18n
  #mac dinh trinh duyet se chi dinh chay ngon ngu nao
  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
# function dung de khi minh dung scope trong routes
# thi khi chuyen trang van giu duoc trang thai cua ngon ngu dang chon
  def default_url_options
   { locale: I18n.locale }
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @products =  Category.find(params[:id]).products
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.limit(8)
    @order_item = current_order.order_items.new
    @categories = Category.all
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

 def destroy
  @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
  respond_to do |format|
    format.html {}
    format.json { head :no_content }
    format.js   { render layout: false }
  end
end
end

app/controllers/order_item_controller.rb
class OrderItemController < ApplicationController
  def create
    @order = current_order
    if exists_product != true
      @order_item = @order.order_items.new(order_item_params)
      @order.save
      flash[:danger] = 'Add to cart success!'
    else
      flash[:danger] = 'Product is exists in Your cart!'
    end
    session[:order_id] = @order.id
  end

  def update
    order_item_ids = params.keys.select{|key| key.include?('quantity')}
    order_items = current_order.order_items
    order_items.each_with_index do |value, index|
    value.update_attributes(quantity: params[order_item_ids[index]].to_i)
    end
    redirect_to :back
  end

  def destroy
    # byebug
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.permit(:quantity, :product_id)
  end

  def exists_product
    current_order.order_items.map{|oi| oi.product.id}.include?(params[:product_id].to_i)
  end

end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  def index
    @order_items = current_order.order_items
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @products =  Category.find(params[:id].to_i).products
    @order_item = current_order.order_items.new
  end

  def show
    @product =  Product.find_by_id params[:id]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews=  Review.all
  end

  def new
  end

  def create
    byebug
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/order/destroy.js.erb
$('.destroy-product').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});
$(".cart-text").html("<%= escape_javascript(render 'share/cart_text') %>")
$(".li_pr2").html("<%= escape_javascript(render 'share/cart') %>")
$(".show_btn_cart").html("<%= escape_javascript(render 'share/btn_show_cart') %>")

app/views/order/show.html.erb
 <div class="col-md-10 col-md-offset-1" style="background-color: #fff;">
  <%= render 'share/side_bar' %>
  <div class="col-md-8">
    <div class="col-xs-12">
      <hr>
      <div class="notice"><%= render 'share/alert', :flash => flash %></div>
      <hr>
    </div>
    <div class="col-md-12">
      <span style="color:#EFEEEA"><b>Home>Your shopping cart</b></span>
    </div>
     <div class="col-md-12" >
      <br>
      <hr class="style15">
      <br>
    </div>
          <!--Shopping Cart table-->
      <div class="table-responsive">
          <table class="table product-table">
              <!--Table head-->
              <thead>
                <tr>
                  <th></th>
                  <th>Product</th>
                  <th>Price</th>
                  <th>Discout</th>
                  <th>Trademark</th>
                  <th>Quantity</th>
                  <th>Amount</th>
                  <th></th>
               </tr>
              </thead>
              <%= form_tag(order_item_path, method: :patch) do %>
              <tbody>
              <% @order_items.each do |oi| %>
                <tr>
                    <th scope="row">
                        <%= image_tag oi.product.image.thumb.url %>
                    </th>
                    <td>
                        <h5><strong><%= oi.product.name %></strong></h5>
                        <p class="text-muted">by Admin</p>
                    </td>
                    <td id="price-<%= oi.product.id %>"><%= oi.product.price %></td>
                    <td><%=number_to_currency oi.product.discount %></td>
                    <td><%= oi.product.trademark %></td>
                    <td>
                        <%= text_field_tag "quantity-#{oi.product.id}", oi.quantity, {id: "quantity-#{oi.product.id}", class: "form-control", style: "width: 44%"} %>
                        <div class="btn-group" data-toggle="buttons">
                            <label class="btn btn-sm btn-primary btn-rounded" onclick="tru(<%=oi.product.id%>)">
                                <input type="radio" name="options" id="option1">&mdash;
                            </label>
                            <label class="btn btn-sm btn-primary btn-rounded" onclick="cong(<%=oi.product.id%>)">
                                <input type="radio" name="options" id="option1">+
                            </label>
                        </div>
                    </td>
                    <td id="amount-<%= oi.product.id %>"><%= number_to_currency oi.product.price * oi.quantity %></td>
                    <td>
                        <%= link_to order_path(oi), method: :delete, remote: true, class: "destroy-product" do %>
                            <span class="glyphicon glyphicon-trash" style="color: black"></span>
                        <% end %>
                    </td>
                </tr>
                <% end %>
                
                <tr>
                    <td colspan="3"></td>
                    <td>
                        <h4><strong>Total</strong></h4></td>
                    <td>
                        <h4><strong> <%= number_to_currency subtotal %></strong></h4></td>
                    <td colspan="3">
                    <!-- <button type="button" class="btn btn-primary">PAYMENT</button> -->
                    <%= link_to "PAYMENT", payment_index_path, class: 'btn btn-primary' %>
                    <%= submit_tag "UPDATE CART", class: 'btn btn-danger btn-md pull-right' %>
                    </td>
                </tr>
              </tbody>
              <% end %>
          </table>
      </div>
  </div>

app/views/order_item/create.js.erb
$(".cart-text").html("<%= escape_javascript(render 'share/cart_text') %>")
$(".li_pr2").html("<%= escape_javascript(render 'share/cart') %>")
$(".notice").html("<%= escape_javascript(render 'share/alert') %>")
$(".show_btn_cart").html("<%= escape_javascript(render 'share/btn_show_cart') %>")

app/views/order_item/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'share/cart_text') %>")
$(".li_pr2").html("<%= escape_javascript(render 'share/cart') %>")
$(".show_btn_cart").html("<%= escape_javascript(render 'share/btn_show_cart') %>")